import { InstrumentStateSnapshot } from '../../types/strategy';

export const SHOW_SAMPLES = false;

// ===================== FUDKII =====================

export const SAMPLE_FUDKII_WATCHING: InstrumentStateSnapshot = {
  scripCode: '535755',
  companyName: 'CRUDEOIL25FEBFUT',
  state: 'WATCHING',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 420000,
  stateDurationMs: 420000,
  currentPrice: 5842.00,
  ofiZscore: 1.35,
  atr: 57.20,
  vpin: 0.48,
  superTrendBullish: false,
  superTrendFlip: false,
  bbPercentB: 0.92,
  bbSqueezing: true,
  activeSetups: [{
    strategyId: 'FUDKII',
    setupDescription: 'FUDKII trigger detected -- BULLISH',
    direction: 'LONG',
    keyLevel: 5867.00,
    watchingStartTime: Date.now() - 420000,
    watchingDurationMs: 420000,
    conditions: [
      { conditionName: 'FUDKII Trigger', passed: true, currentValue: 78, requiredValue: 0, comparison: '>=', progressPercent: 100, displayValue: '78.0' },
      { conditionName: 'Direction', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'BULLISH' },
      { conditionName: 'Gate Validation', passed: false, currentValue: 42, requiredValue: 50, comparison: '>=', progressPercent: 84, displayValue: '42.0 / 50.0' },
    ],
    progressPercent: 60,
    blockingCondition: 'Gate validation pending -- OFI confirmation needed',
    readyForEntry: false,
    notReadyReason: 'Gate checks: OFI Z-Score below threshold (1.35 < 1.50)',
    qualityTier: 'B',
  }],
  signalsToday: 1,
  maxSignalsPerDay: 5,
  cooldownRemainingMs: 0,
};

export const SAMPLE_FUDKII_READY: InstrumentStateSnapshot = {
  scripCode: '535755-R',
  companyName: 'CRUDEOIL25FEBFUT',
  state: 'READY',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 45000,
  stateDurationMs: 45000,
  currentPrice: 5858.00,
  ofiZscore: 2.10,
  atr: 57.20,
  vpin: 0.62,
  superTrendBullish: true,
  superTrendFlip: true,
  bbPercentB: 1.15,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'FUDKII',
    setupDescription: 'FUDKII READY -- all gates passed',
    direction: 'LONG',
    keyLevel: 5867.00,
    watchingStartTime: Date.now() - 465000,
    watchingDurationMs: 465000,
    conditions: [
      { conditionName: 'FUDKII Trigger', passed: true, currentValue: 82, requiredValue: 0, comparison: '>=', progressPercent: 100, displayValue: '82.0' },
      { conditionName: 'Direction', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'BULLISH' },
      { conditionName: 'Gate Validation', passed: true, currentValue: 55, requiredValue: 50, comparison: '>=', progressPercent: 100, displayValue: '55.0 / 50.0' },
    ],
    progressPercent: 100,
    readyForEntry: true,
    qualityTier: 'A',
  }],
  signalsToday: 1,
  maxSignalsPerDay: 5,
  cooldownRemainingMs: 0,
};

export const SAMPLE_FUDKII_POSITIONED: InstrumentStateSnapshot = {
  scripCode: '535755-P',
  companyName: 'CRUDEOIL25FEBFUT',
  state: 'POSITIONED',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 8100000,
  stateDurationMs: 8100000,
  currentPrice: 5908.50,
  ofiZscore: 0.85,
  atr: 57.20,
  vpin: 0.44,
  superTrendBullish: true,
  superTrendFlip: false,
  bbPercentB: 0.72,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'FUDKII',
    setupDescription: 'FUDKII position active',
    direction: 'LONG',
    keyLevel: 5981.00,
    watchingStartTime: Date.now() - 8565000,
    watchingDurationMs: 8565000,
    conditions: [
      { conditionName: 'FUDKII Trigger', passed: true, currentValue: 82, requiredValue: 0, comparison: '>=', progressPercent: 100, displayValue: '82.0' },
      { conditionName: 'Direction', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'BULLISH' },
      { conditionName: 'Gate Validation', passed: true, currentValue: 55, requiredValue: 50, comparison: '>=', progressPercent: 100, displayValue: 'PASS' },
    ],
    progressPercent: 100,
    readyForEntry: true,
    qualityTier: 'A',
  }],
  position: {
    direction: 'LONG',
    entryPrice: 5867.00,
    currentPrice: 5908.50,
    stopLoss: 5810.00,
    takeProfit: 5981.00,
    unrealizedPnl: 1240.50,
    unrealizedPnlPercent: 2.12,
    entryTime: Date.now() - 8100000,
    holdingDurationMs: 8100000,
    strategyId: 'FUDKII',
    signalId: 'sig-fudkii-001',
  },
  signalsToday: 2,
  maxSignalsPerDay: 5,
  cooldownRemainingMs: 0,
};

// ===================== PIVOT =====================

export const SAMPLE_PIVOT_WATCHING: InstrumentStateSnapshot = {
  scripCode: '500325',
  companyName: 'RELIANCE',
  state: 'WATCHING',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 1800000,
  stateDurationMs: 1800000,
  currentPrice: 1285.50,
  ofiZscore: 0.62,
  atr: 18.40,
  vpin: 0.38,
  superTrendBullish: true,
  superTrendFlip: false,
  bbPercentB: 0.55,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'PIVOT_CONFLUENCE',
    setupDescription: 'Pivot confluence building -- BULLISH bias',
    direction: 'LONG',
    keyLevel: 1302.00,
    watchingStartTime: Date.now() - 1800000,
    watchingDurationMs: 1800000,
    conditions: [
      { conditionName: 'HTF Bias', passed: true, currentValue: 85, requiredValue: 30, comparison: '>=', progressPercent: 100, displayValue: 'BULLISH (85%)' },
      { conditionName: 'LTF Confirm', passed: true, currentValue: 62, requiredValue: 50, comparison: '>=', progressPercent: 100, displayValue: 'Aligned 62%' },
      { conditionName: 'Pivot Levels', passed: false, currentValue: 1, requiredValue: 2, comparison: '>=', progressPercent: 50, displayValue: '1 of 2 levels' },
      { conditionName: 'R:R Ratio', passed: false, currentValue: 1.2, requiredValue: 1.5, comparison: '>=', progressPercent: 80, displayValue: '1.20:1' },
    ],
    progressPercent: 65,
    blockingCondition: 'Pivot confluence insufficient -- 1 of 2 levels nearby',
    readyForEntry: false,
    notReadyReason: 'Need 2+ pivot levels nearby and R:R >= 1.5:1',
    qualityTier: 'B',
  }],
  signalsToday: 0,
  maxSignalsPerDay: 3,
  cooldownRemainingMs: 0,
};

export const SAMPLE_PIVOT_READY: InstrumentStateSnapshot = {
  scripCode: '500325-R',
  companyName: 'RELIANCE',
  state: 'READY',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 30000,
  stateDurationMs: 30000,
  currentPrice: 1294.80,
  ofiZscore: 1.45,
  atr: 18.40,
  vpin: 0.55,
  superTrendBullish: true,
  superTrendFlip: false,
  bbPercentB: 0.78,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'PIVOT_CONFLUENCE',
    setupDescription: 'Pivot confluence READY -- all conditions met',
    direction: 'LONG',
    keyLevel: 1302.00,
    watchingStartTime: Date.now() - 1830000,
    watchingDurationMs: 1830000,
    conditions: [
      { conditionName: 'HTF Bias', passed: true, currentValue: 88, requiredValue: 30, comparison: '>=', progressPercent: 100, displayValue: 'BULLISH (88%)' },
      { conditionName: 'LTF Confirm', passed: true, currentValue: 75, requiredValue: 50, comparison: '>=', progressPercent: 100, displayValue: 'Aligned 75%' },
      { conditionName: 'Pivot Levels', passed: true, currentValue: 3, requiredValue: 2, comparison: '>=', progressPercent: 100, displayValue: 'Daily R1 + Weekly P + CPR' },
      { conditionName: 'R:R Ratio', passed: true, currentValue: 2.1, requiredValue: 1.5, comparison: '>=', progressPercent: 100, displayValue: '2.10:1' },
    ],
    progressPercent: 100,
    readyForEntry: true,
    qualityTier: 'A_PLUS',
    mtfAnalysis: {
      htfTimeframe: 'Daily',
      ltfTimeframe: '15m',
      htfBias: 'BULLISH',
      ltfBias: 'BULLISH',
      biasAligned: true,
      htfStructure: 'Higher Highs',
      ltfStructure: 'CHoCH Bullish',
      swingHigh: 1320.00,
      swingLow: 1260.00,
      equilibrium: 1290.00,
      zonePosition: 'EQUILIBRIUM',
      rangePositionPercent: 58,
      swingSizePercent: 4.76,
      isUpswing: true,
      flowStatus: 'PASS',
      flowInterpretation: 'FII net buyers, OI buildup supports long',
      flowReason: 'Call OI addition at 1300 strike',
      completedSteps: 5,
      totalSteps: 5,
      completedStepNames: ['HTF Bias', 'LTF Confirm', 'Pivot Level', 'SMC Zone', 'R:R Valid'],
      missingStepNames: [],
      coreRequirementsMet: true,
      fullSequenceMet: true,
      qualityTier: 'A_PLUS',
      qualityTierDisplay: 'A+',
      qualitySummary: 'All 5 conditions met with strong HTF-LTF alignment',
      qualityReasons: ['HTF BULLISH 88%', '3 pivot levels', 'In Order Block', 'R:R 2.1:1'],
      qualityScore: 92,
      atHtfDemand: true,
      atHtfSupply: false,
      ltfSweepDetected: true,
      ltfSweepSide: 'BUY_SIDE',
      ltfChochDetected: true,
      ltfChochDirection: 'BULLISH',
      ltfBosDetected: false,
    },
  }],
  signalsToday: 0,
  maxSignalsPerDay: 3,
  cooldownRemainingMs: 0,
};

export const SAMPLE_PIVOT_POSITIONED: InstrumentStateSnapshot = {
  scripCode: '500325-P',
  companyName: 'RELIANCE',
  state: 'POSITIONED',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 3600000,
  stateDurationMs: 3600000,
  currentPrice: 1298.40,
  ofiZscore: 0.92,
  atr: 18.40,
  vpin: 0.42,
  superTrendBullish: true,
  superTrendFlip: false,
  bbPercentB: 0.68,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'PIVOT_CONFLUENCE',
    setupDescription: 'Pivot confluence position active',
    direction: 'LONG',
    keyLevel: 1302.00,
    watchingStartTime: Date.now() - 5430000,
    watchingDurationMs: 5430000,
    conditions: [
      { conditionName: 'HTF Bias', passed: true, currentValue: 88, requiredValue: 30, comparison: '>=', progressPercent: 100, displayValue: 'BULLISH (88%)' },
      { conditionName: 'LTF Confirm', passed: true, currentValue: 75, requiredValue: 50, comparison: '>=', progressPercent: 100, displayValue: 'Aligned 75%' },
      { conditionName: 'Pivot Levels', passed: true, currentValue: 3, requiredValue: 2, comparison: '>=', progressPercent: 100, displayValue: '3 levels' },
      { conditionName: 'R:R Ratio', passed: true, currentValue: 2.1, requiredValue: 1.5, comparison: '>=', progressPercent: 100, displayValue: '2.10:1' },
    ],
    progressPercent: 100,
    readyForEntry: true,
    qualityTier: 'A_PLUS',
  }],
  position: {
    direction: 'LONG',
    entryPrice: 1295.00,
    currentPrice: 1298.40,
    stopLoss: 1271.80,
    takeProfit: 1320.00,
    unrealizedPnl: 340.00,
    unrealizedPnlPercent: 0.26,
    entryTime: Date.now() - 3600000,
    holdingDurationMs: 3600000,
    strategyId: 'PIVOT_CONFLUENCE',
    signalId: 'sig-pivot-001',
  },
  signalsToday: 1,
  maxSignalsPerDay: 3,
  cooldownRemainingMs: 0,
};

// ===================== MICROALPHA =====================

export const SAMPLE_MICRO_WATCHING: InstrumentStateSnapshot = {
  scripCode: '500180',
  companyName: 'HDFCBANK',
  state: 'WATCHING',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 120000,
  stateDurationMs: 120000,
  currentPrice: 1642.30,
  ofiZscore: -0.85,
  atr: 22.10,
  vpin: 0.51,
  superTrendBullish: false,
  superTrendFlip: false,
  bbPercentB: 0.18,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'MICROALPHA',
    setupDescription: 'MicroAlpha conviction building -- BEARISH',
    direction: 'SHORT',
    keyLevel: 1618.50,
    watchingStartTime: Date.now() - 120000,
    watchingDurationMs: 120000,
    conditions: [
      { conditionName: 'Conviction', passed: false, currentValue: 33, requiredValue: 40, comparison: '>=', progressPercent: 82, displayValue: '33 / 40' },
      { conditionName: 'Mode Entry', passed: false, currentValue: 0, requiredValue: 1, comparison: '==', progressPercent: 0, displayValue: 'TREND_FOLLOWING -- pending' },
      { conditionName: 'Momentum', passed: false, currentValue: 0, requiredValue: 1, comparison: '==', progressPercent: 0, displayValue: 'Stalled' },
      { conditionName: 'Direction', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'BEARISH confirmed' },
    ],
    progressPercent: 35,
    blockingCondition: 'Conviction at 33 -- need 40 to trigger',
    readyForEntry: false,
    notReadyReason: 'Conviction score below threshold; momentum stalled',
    qualityTier: 'C',
  }],
  signalsToday: 0,
  maxSignalsPerDay: 8,
  cooldownRemainingMs: 0,
};

export const SAMPLE_MICRO_READY: InstrumentStateSnapshot = {
  scripCode: '500180-R',
  companyName: 'HDFCBANK',
  state: 'READY',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 15000,
  stateDurationMs: 15000,
  currentPrice: 1638.50,
  ofiZscore: -1.92,
  atr: 22.10,
  vpin: 0.68,
  superTrendBullish: false,
  superTrendFlip: true,
  bbPercentB: -0.05,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'MICROALPHA',
    setupDescription: 'MicroAlpha READY -- TREND_FOLLOWING mode',
    direction: 'SHORT',
    keyLevel: 1618.50,
    watchingStartTime: Date.now() - 135000,
    watchingDurationMs: 135000,
    conditions: [
      { conditionName: 'Conviction', passed: true, currentValue: 48, requiredValue: 40, comparison: '>=', progressPercent: 100, displayValue: '48 / 40' },
      { conditionName: 'Mode Entry', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'TREND_FOLLOWING -- met' },
      { conditionName: 'Momentum', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'Accelerating' },
      { conditionName: 'Direction', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'BEARISH confirmed' },
    ],
    progressPercent: 100,
    readyForEntry: true,
    qualityTier: 'A',
  }],
  signalsToday: 0,
  maxSignalsPerDay: 8,
  cooldownRemainingMs: 0,
};

export const SAMPLE_MICRO_POSITIONED: InstrumentStateSnapshot = {
  scripCode: '500180-P',
  companyName: 'HDFCBANK',
  state: 'POSITIONED',
  stateTimestamp: Date.now(),
  stateEntryTime: Date.now() - 540000,
  stateDurationMs: 540000,
  currentPrice: 1628.70,
  ofiZscore: -1.15,
  atr: 22.10,
  vpin: 0.58,
  superTrendBullish: false,
  superTrendFlip: false,
  bbPercentB: 0.12,
  bbSqueezing: false,
  activeSetups: [{
    strategyId: 'MICROALPHA',
    setupDescription: 'MicroAlpha position active -- TREND_FOLLOWING',
    direction: 'SHORT',
    keyLevel: 1618.50,
    watchingStartTime: Date.now() - 675000,
    watchingDurationMs: 675000,
    conditions: [
      { conditionName: 'Conviction', passed: true, currentValue: 48, requiredValue: 40, comparison: '>=', progressPercent: 100, displayValue: '48 / 40' },
      { conditionName: 'Mode Entry', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'TREND_FOLLOWING' },
      { conditionName: 'Momentum', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'Accelerating' },
      { conditionName: 'Direction', passed: true, currentValue: 1, requiredValue: 1, comparison: '==', progressPercent: 100, displayValue: 'BEARISH' },
    ],
    progressPercent: 100,
    readyForEntry: true,
    qualityTier: 'A',
  }],
  position: {
    direction: 'SHORT',
    entryPrice: 1638.50,
    currentPrice: 1628.70,
    stopLoss: 1664.20,
    takeProfit: 1618.50,
    unrealizedPnl: 980.00,
    unrealizedPnlPercent: 0.60,
    entryTime: Date.now() - 540000,
    holdingDurationMs: 540000,
    strategyId: 'MICROALPHA',
    signalId: 'sig-micro-001',
  },
  signalsToday: 1,
  maxSignalsPerDay: 8,
  cooldownRemainingMs: 0,
};

// Grouped by strategy for easy injection
export const FUDKII_SAMPLES = [SAMPLE_FUDKII_WATCHING, SAMPLE_FUDKII_READY, SAMPLE_FUDKII_POSITIONED];
export const PIVOT_SAMPLES = [SAMPLE_PIVOT_WATCHING, SAMPLE_PIVOT_READY, SAMPLE_PIVOT_POSITIONED];
export const MICRO_SAMPLES = [SAMPLE_MICRO_WATCHING, SAMPLE_MICRO_READY, SAMPLE_MICRO_POSITIONED];
export const ALL_SAMPLES = [...FUDKII_SAMPLES, ...PIVOT_SAMPLES, ...MICRO_SAMPLES];
